### ISSUE TITLE
query API quirks

### ISSUE THREAD

**Issue by mattvonrocketstein** [CollabRx/callisto#6]
I'll mention here a few things I found surprising about Query behavior.   I consider these things bugs, but I can also see an argument being made that they are not (I don't know much about the existing conventions used in ecto, etc)  If other people agree they are bugs I can make patches.

First quirk: pipe-lining with an individual query overwrites rather than appending.  

```
iex(1)> %Query{} |> Query.merge("x")  |> Query.merge("y") |> to_string
"MERGE y"
```

I expected to see  something like `MERGE x\nMERGE y`.  I think appending makes more sense, but if that's undesirable then probably an error should be thrown instead of the silent overwrite.  The workaround for the existing behavior often seems more verbose and cumbersome.  For example:

```
q = %Query{} # empty query
cypher = [ Query.merge(q, "x"), Query.merge(q, "y")]
|> Enum.map(&to_string/1)
|> Enum.join("\n")
```

Second quirk.  As in the code above, setting up an empty `%Query{}` is quite a common thing in my code.  While `Query.merge(%Query() , "x")` formula is probably more idiomatic elixir it does seem very useful to add a `Query.merge/1` function clause for bitstrings.  In other words `Query.merge("pattern")` would have the empty %Query{} implied.  Ditto for Query.match, etc.  The current behavior is undefined, see trace below.  

```
iex(5)> Query.merge("x")
** (UndefinedFunctionError) function Callisto.Query.merge/1 is undefined or private. Did you mean one of:

      * merge/2
```

**Comment by dotdotdotpaul** [comment]
Second quirk first:  Yes, I've definitely been thinking all the Query methods should basically provide a default %Query{} arg if one isn't piped in or otherwise provided.  Just haven't gotten around to it.

With regards to the first quirk, it's a quirk.  When I started tinkering, I had the idea that you'd be more likely to want to replace a part of the query than continue extending it.  This is also partly because there's a lot of connective tissue in Cypher queries than, say, SQL -- the variable used in a MATCH needs to be replicated in the RETURN, and may be used in the SET.  Also, originally it seemed like some parts of the syntax are mutually exclusive, although over time, I've realized those are pretty few and far between -- DELETE and RETURN, for example (although even then, I'm not entirely sure they are mutually exclusive, so long as you don't attempt to return what you deleted).

However, insofar as your example goes, you don't need to jump those hoops, because you don't need multiple MERGE lines in the first place.  :)

```
%Query{} |> Query.merge(a: %{}, b: %{}) |> to_string
MERGE (a), (b)

```

That said, I don't see much reason why it couldn't accumulate fragments going forward, although it does mean you won't be able to replace fragments without reconstructing a query from scratch.  I'm not so super-familiar with Cypher (yet) to know if that's really a "big deal" or not...

**Comment by mattvonrocketstein** [comment]
> However, insofar as your example goes, you don't need to jump those hoops, because you don't need multiple MERGE lines in the first place. :)

Sorry for the slow reply, but is this really true in all (or any) versions of neo4j?  I get a SyntaxError back from the server with lines like  "MERGE (u1:node {title: '1770'}), (u2:node {title: '1771'}) ".  

```
%{"code" => "Neo.ClientError.Statement.InvalidSyntax",
    "message" => "Invalid input ',': expected whitespace, a relationship pattern, ON, START, MATCH, MERGE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, RETURN, UNION, ';' or end of input (line 1, column 36)
```

Also [this stack overflow](http://stackoverflow.com/questions/21605388/is-there-a-way-to-add-multiple-nodes-with-properties-in-neo4j-with-cypher) seems to support the fact that multiple merge statements might be needed.

**Comment by mkompanets** [comment]
@mattvonrocketstein thank you for bringing that up.  That was unexpected.  It seems to work fine for `MATCH` and `CREATE`, but it is not a valid `MERGE`.  This issue https://github.com/neo4j/neo4j/issues/2973 explains the reasoning behind it.  Comma separated  `MATCH` and `CREATE` can be internally broken down into separate statements.  `MERGE` cannot be broken down like that.

Having said that, the issues you brought up here were [addressed](https://github.com/CollabRx/callisto/pull/7) and Callisto now supports statements like `Query.merge("x")` without having to pass in an empty `%Query{}` and pipelined queries like `Query.merge("x")  |> Query.merge("y") |> to_string` will return `MERGE x\nMERGE y` instead of being overridden.

**Comment by dotdotdotpaul** [comment]
Well, I've never said I was a Neo4j expert.  :)  Strange that `MERGE` can't work the same way.  Guess we should also then make sure Callisto separates multiple `MERGE` structures if passed together on a single call...

**Comment by mattvonrocketstein** [comment]
No worries.. I was surprised myself and almost convinced you guys just had a newer version of the server than I did.  I just made a PR.  Should the added doctests go into the utest suite instead?
